### ISSUE TITLE
关于text2img参数问题

### ISSUE THREAD

**Issue by CNDotaBest** [zhuqingsong59/sdwebuiapi-flask#1]
你好，请问您有text2img api参数的相关介绍吗？

**Comment by zhuqingsong59** [comment]
![image](https://github.com/zhuqingsong59/sdwebuiapi-flask/assets/13329506/b49d3f80-649a-4b6b-a302-9c700308e5fb)
https://github.com/mix1009/sdwebuiapi
你可以参考这个库里的函数入参，大部分跟sd-webui上是对应的
